#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#                                


# Core Colors
background            #f6fafe
foreground            #171c1f
selection_foreground  #1a6585
selection_background  #ffffff
cursor                #1a6585
cursor_text_color     #f6fafe

# Regular Colors
color0  #f6fafe               
color1  #ba1a1a                 
color2  #1a6585               
color3  #605a7d              
color4  #001e2c  
color5  #091e28
color6  #4e616d             
color7  #171c1f            

# Bright Colors
color8  #f6fafe         
color9  #ba1a1a                  
color10 #1a6585                
color11 #605a7d               
color12 #001e2c   
color13 #091e28 
color14 #4e616d              
color15 #171c1f             
