#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┏┏┓┳┓┓ ┏┓┳┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣┫┗┫┃┃┣┫┃ ┣┫┃┃┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┛┗┛┗┻┛
#                                    



# Image Path
$image = /home/thenyxorion/Pictures/Wallpapers/.homeless/arch.png


$foreground = rgba(171c1fff)
$background = rgba(f6fafeff)

$color0 = rgba(f6fafeff)
$color1 = rgba(c2e8ffff)
$color2 = rgba(d1e5f3ff)
$color3 = rgba(e6deffff)
$color4 = rgba(ba1a1aff)
$color5 = rgba(1a6585ff)
$color6 = rgba(4e616dff)
$color7 = rgba(171c1fff)
$color8 = rgba(f6fafeff)
$color9 = rgba(c2e8ffff)
$color10 = rgba(d1e5f3ff)
$color11 = rgba(e6deffff)
$color12 = rgba(ba1a1aff)
$color13 = rgba(1a6585ff)
$color14 = rgba(4e616dff)
$color15 = rgba(171c1fff)
